# Generated by Django 5.1.5 on 2025-04-04 00:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadocalibracion',
            options={'ordering': ['orden'], 'verbose_name_plural': 'Estados de Calibración'},
        ),
        migrations.AlterModelOptions(
            name='historialequipo',
            options={'get_latest_by': 'fecha_cambio', 'ordering': ['-fecha_cambio'], 'verbose_name_plural': 'Historial de Equipos'},
        ),
        migrations.AddField(
            model_name='estadocalibracion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='estadocalibracion',
            name='orden',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historialequipo',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.estadocalibracion'),
        ),
        migrations.AlterField(
            model_name='historialequipo',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
