# Generated by Django 5.1.5 on 2025-04-06 08:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_estadocalibracion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialequipo',
            options={'get_latest_by': 'fecha_cambio', 'ordering': ['-fecha_cambio']},
        ),
        migrations.AddField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
