# Generated by Django 5.1.5 on 2025-04-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_historialequipo_options_usuario_date_joined'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadocalibracion',
            options={'ordering': ['orden']},
        ),
        migrations.AlterField(
            model_name='estadocalibracion',
            name='nombre_estado',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
